"""
mandates.py — Data models for the AP2 mandate lifecycle.

Defines the typed mandate objects that flow through the edge gateway:

    Intent Mandate  →  Cart Mandate  →  (Mediator)  →  Attestation  →  Payment Mandate

The Mediator is treated as an untrusted third party; every attestation
it returns must pass RFC 3161 timestamp verification and Merkle-root
proof before a Payment Mandate is released.
"""

from __future__ import annotations

import hashlib
import time
import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class MandateStatus(str, Enum):
    PENDING = "pending"
    ATTESTED = "attested"
    VERIFIED = "verified"
    RELEASED = "released"
    REJECTED = "rejected"


class IntentMandate(BaseModel):
    """
    Captures the user's stated trading intent before any cart is built.

    Extracted by the ``before_model`` interceptor from the ADK agent
    context (LLM request content, session state, tool parameters).
    """

    mandate_id: str = Field(default_factory=lambda: f"intent-{uuid.uuid4().hex[:12]}")
    user_id: str
    session_id: str = ""
    intent_description: str
    constraints: dict[str, Any] = Field(default_factory=dict)
    max_budget_tokens: int = 0
    timestamp: float = Field(default_factory=time.time)

    def content_hash(self) -> str:
        """Deterministic SHA-256 over the canonical intent fields."""
        canonical = (
            f"{self.mandate_id}|{self.user_id}|{self.intent_description}"
            f"|{self.max_budget_tokens}|{self.timestamp}"
        )
        return hashlib.sha256(canonical.encode()).hexdigest()


class CartItem(BaseModel):
    """A single line-item generated by the agent."""

    skill_id: str
    provider_id: str
    amount_tokens: int
    description: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class CartMandate(BaseModel):
    """
    The agent-generated cart that satisfies an Intent Mandate.

    Extracted by the ``after_model`` interceptor when the LLM emits
    tool calls or structured output describing the purchases.
    """

    mandate_id: str = Field(default_factory=lambda: f"cart-{uuid.uuid4().hex[:12]}")
    intent_mandate_id: str
    items: list[CartItem] = Field(default_factory=list)
    total_tokens: int = 0
    timestamp: float = Field(default_factory=time.time)

    def content_hash(self) -> str:
        """Deterministic SHA-256 over the canonical cart fields."""
        items_canon = "|".join(
            f"{i.skill_id}:{i.provider_id}:{i.amount_tokens}" for i in self.items
        )
        canonical = (
            f"{self.mandate_id}|{self.intent_mandate_id}"
            f"|{items_canon}|{self.total_tokens}|{self.timestamp}"
        )
        return hashlib.sha256(canonical.encode()).hexdigest()


class PreDisputeAttestation(BaseModel):
    """
    Payload returned by the Mediator after reviewing both mandates.

    Contains an RFC 3161 timestamp token (DER-encoded, base-64) and a
    Merkle root that commits to the intent + cart hashes.  Both MUST be
    verified before the gateway releases the Payment Mandate.
    """

    attestation_id: str
    intent_hash: str
    cart_hash: str
    merkle_root: str
    merkle_proof: list[MerkleProofNode] = Field(default_factory=list)
    rfc3161_token: str  # base-64 encoded DER TimeStampToken
    tsa_certificate_pem: str  # PEM of the TSA that signed the token
    mediator_id: str
    status: MandateStatus = MandateStatus.ATTESTED
    timestamp: float = Field(default_factory=time.time)


class MerkleProofNode(BaseModel):
    """One node in a Merkle inclusion proof (hash + direction)."""

    hash: str
    direction: str  # "left" or "right"


# Pydantic v2 forward-ref rebuild — MerkleProofNode is referenced before
# its definition in PreDisputeAttestation.
PreDisputeAttestation.model_rebuild()


class PaymentMandate(BaseModel):
    """
    The final AP2 payment instruction released to the payment processor.

    Only constructed after cryptographic verification of the attestation.
    When ``status`` is ``REJECTED``, the ``error`` dict carries a
    JSON-RPC 2.0 error object with code, message, and optional data.
    """

    mandate_id: str = Field(default_factory=lambda: f"pay-{uuid.uuid4().hex[:12]}")
    attestation_id: str
    intent_mandate_id: str
    cart_mandate_id: str
    escrow_ids: list[str] = Field(default_factory=list)
    total_tokens: int = 0
    status: MandateStatus = MandateStatus.VERIFIED
    error: dict[str, Any] | None = None
    released_at: float = 0.0
    timestamp: float = Field(default_factory=time.time)
